"""Render daily digest email.

Two outputs:
  - Plain-text summary suitable for email body fallback or terminal output
  - HTML email with a clean editorial layout

Sections (per pathogen, in order):
  1. New alerts (events from diff) — the action items
  2. Active mixed clusters (human + nonhuman) — surveillance overview
  3. Tight cross-cluster near-neighbors — early warning

Designed to be glanceable on mobile and informative on desktop.
"""

from __future__ import annotations

import html
import logging
from collections import defaultdict
from datetime import date, datetime
from typing import Iterable

from . import config
from .cluster import Cluster, CrossClusterNearNeighbor
from .state import Event, EventType

log = logging.getLogger(__name__)


EVENT_LABEL = {
    EventType.NEW_HUMAN_CLUSTER: "New human cluster",
    EventType.NEW_HUMAN_IN_CLUSTER: "Human case added to cluster",
    EventType.NEW_NONHUMAN_NEAR_HUMAN: "Nonhuman isolate added to human cluster",
}


def _cluster_url(pds: str) -> str:
    return f"https://www.ncbi.nlm.nih.gov/pathogens/isolates/#{pds}"


def _isolate_url(pdt: str) -> str:
    return f"https://www.ncbi.nlm.nih.gov/pathogens/isolates/#{pdt}"


def _fmt_sources(c: Cluster) -> str:
    src = sorted(c.nonhuman_sources)
    if not src:
        return "—"
    if len(src) > 4:
        return ", ".join(src[:4]) + f" (+{len(src)-4} more)"
    return ", ".join(src)


def _fmt_countries(c: Cluster) -> str:
    countries = sorted(c.countries)
    if not countries:
        return "—"
    if len(countries) > 5:
        return ", ".join(countries[:5]) + f" (+{len(countries)-5})"
    return ", ".join(countries)


# ---------------------------------------------------------------------------
# Plain text
# ---------------------------------------------------------------------------

def render_text(
    run_date: date,
    events_by_pathogen: dict[str, list[Event]],
    mixed_clusters_by_pathogen: dict[str, list[Cluster]],
    near_neighbors_by_pathogen: dict[str, dict[int, list[CrossClusterNearNeighbor]]],
) -> str:
    lines: list[str] = []
    total_events = sum(len(v) for v in events_by_pathogen.values())
    lines.append(f"NCBI Pathogen Detection — Daily Alert Digest")
    lines.append(f"Run date: {run_date.isoformat()}")
    lines.append(f"Total new events: {total_events}")
    lines.append("=" * 72)

    for pathogen in config.PATHOGENS:
        events = events_by_pathogen.get(pathogen, [])
        mixed = mixed_clusters_by_pathogen.get(pathogen, [])
        neighbors = near_neighbors_by_pathogen.get(pathogen, {})

        lines.append("")
        lines.append(f"### {pathogen}")
        lines.append("-" * 72)

        # Events
        if events:
            lines.append(f"NEW EVENTS ({len(events)}):")
            for ev in events[:config.MAX_CLUSTERS_PER_SECTION]:
                lines.append(f"  [{EVENT_LABEL[ev.event_type]}] {ev.summary}")
                lines.append(f"    Cluster: {_cluster_url(ev.pds_acc)}")
                if ev.new_pdt_accs:
                    shown = ev.new_pdt_accs[:5]
                    extra = "" if len(ev.new_pdt_accs) <= 5 else f" (+{len(ev.new_pdt_accs)-5} more)"
                    lines.append(f"    New isolates: {', '.join(shown)}{extra}")
        else:
            lines.append("No new alert events.")

        # Mixed clusters
        if mixed:
            lines.append("")
            lines.append(f"ACTIVE MIXED CLUSTERS ({len(mixed)} shown, most-recent first):")
            for c in mixed[:config.MAX_CLUSTERS_PER_SECTION]:
                tight = c.tightest_human_min_same
                tight_str = f"≤{tight} SNPs" if tight is not None else "n/a"
                lines.append(
                    f"  {c.pds_acc}: {c.n_human} human / {c.n_nonhuman} nonhuman; "
                    f"tightest human gap: {tight_str}; "
                    f"latest: {c.latest_collection or 'n/a'}; "
                    f"sources: {_fmt_sources(c)}; "
                    f"geo: {_fmt_countries(c)}"
                )

        # Near-neighbors
        for thresh in config.SNP_THRESHOLDS:
            nns = neighbors.get(thresh, [])
            if not nns:
                continue
            lines.append("")
            lines.append(f"TIGHT NONHUMAN CROSS-CLUSTER NEIGHBORS (≤{thresh} SNPs): {len(nns)}")
            for n in nns[:config.MAX_ISOLATES_PER_CLUSTER]:
                iso = n.isolate
                lines.append(
                    f"  {iso.pdt_acc} ({iso.isolation_source or iso.host or '?'}): "
                    f"min_diff={iso.min_diff}; cluster {iso.pds_acc}; "
                    f"collected {iso.collection_date or '?'}; geo {iso.geo_loc_name or '?'}"
                )

    lines.append("")
    lines.append("=" * 72)
    lines.append("Generated by pathogen-alerts. Source: NCBI Pathogen Detection.")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

# Inline CSS only — email clients strip <style> blocks unpredictably.
_HTML_STYLE = """
body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a;
       max-width: 760px; margin: 0 auto; padding: 24px; line-height: 1.5;
       background: #fafaf7; }
h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -0.01em; }
h2 { font-size: 17px; margin: 32px 0 8px; padding-bottom: 4px;
     border-bottom: 2px solid #2a2a2a; letter-spacing: -0.005em; }
h3 { font-size: 13px; margin: 20px 0 8px; text-transform: uppercase;
     letter-spacing: 0.08em; color: #555; font-weight: 700; }
.meta { color: #666; font-size: 13px; margin-bottom: 16px; }
table { border-collapse: collapse; width: 100%; margin: 8px 0 16px;
        font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;
        font-size: 13px; }
th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e2e2dc;
         vertical-align: top; }
th { background: #ececeb; font-weight: 600; }
tr:nth-child(even) td { background: #f4f4f0; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 3px;
         font-size: 11px; font-weight: 600; text-transform: uppercase;
         letter-spacing: 0.04em; }
.badge-new   { background: #c41e3a; color: white; }
.badge-grow  { background: #d97706; color: white; }
.badge-mixed { background: #1f6feb; color: white; }
.badge-near  { background: #6b21a8; color: white; }
.empty { color: #888; font-style: italic; font-size: 13px; }
a { color: #1f6feb; text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: ui-monospace, 'SF Mono', Menlo, monospace; font-size: 12px;
       background: #ececeb; padding: 1px 5px; border-radius: 3px; }
.footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd;
          color: #888; font-size: 12px; font-family: -apple-system, sans-serif; }
.count { color: #666; font-weight: normal; font-size: 14px; }
"""

_BADGE_FOR_EVENT = {
    EventType.NEW_HUMAN_CLUSTER: ("badge-new", "New"),
    EventType.NEW_HUMAN_IN_CLUSTER: ("badge-grow", "Human added"),
    EventType.NEW_NONHUMAN_NEAR_HUMAN: ("badge-mixed", "Nonhuman added"),
}


def _h(s) -> str:
    """HTML-escape, treating None as empty."""
    return html.escape("" if s is None else str(s))


def _events_table(events: list[Event]) -> str:
    if not events:
        return '<p class="empty">No new alert events.</p>'
    rows = []
    for ev in events[:config.MAX_CLUSTERS_PER_SECTION]:
        cls, label = _BADGE_FOR_EVENT[ev.event_type]
        new_iso_html = ""
        if ev.new_pdt_accs:
            shown = ev.new_pdt_accs[:5]
            extra = "" if len(ev.new_pdt_accs) <= 5 else f" (+{len(ev.new_pdt_accs)-5})"
            new_iso_html = ", ".join(f"<code>{_h(p)}</code>" for p in shown) + extra
        rows.append(
            f"<tr>"
            f"<td><span class='badge {cls}'>{label}</span></td>"
            f"<td><a href='{_h(_cluster_url(ev.pds_acc))}'><code>{_h(ev.pds_acc)}</code></a></td>"
            f"<td>{_h(ev.summary)}</td>"
            f"<td>{new_iso_html}</td>"
            f"</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Type</th><th>Cluster</th><th>Summary</th><th>New isolates</th>"
        "</tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _mixed_table(mixed: list[Cluster]) -> str:
    if not mixed:
        return '<p class="empty">No active mixed clusters in the recent window.</p>'
    rows = []
    for c in mixed[:config.MAX_CLUSTERS_PER_SECTION]:
        tight = c.tightest_human_min_same
        tight_str = f"≤{tight}" if tight is not None else "—"
        rows.append(
            f"<tr>"
            f"<td><a href='{_h(_cluster_url(c.pds_acc))}'><code>{_h(c.pds_acc)}</code></a></td>"
            f"<td>{c.n_human}</td>"
            f"<td>{c.n_nonhuman}</td>"
            f"<td>{tight_str}</td>"
            f"<td>{_h(c.latest_collection or '—')}</td>"
            f"<td>{_h(_fmt_sources(c))}</td>"
            f"<td>{_h(_fmt_countries(c))}</td>"
            f"</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Cluster</th><th>Hu</th><th>Non-Hu</th><th>Tightest SNP gap</th>"
        "<th>Latest</th><th>Nonhuman sources</th><th>Geography</th>"
        "</tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _neighbors_table(nns: list[CrossClusterNearNeighbor], threshold: int) -> str:
    if not nns:
        return ""
    rows = []
    for n in nns[:config.MAX_ISOLATES_PER_CLUSTER]:
        iso = n.isolate
        rows.append(
            f"<tr>"
            f"<td><a href='{_h(_isolate_url(iso.pdt_acc))}'><code>{_h(iso.pdt_acc)}</code></a></td>"
            f"<td>{_h(iso.min_diff)}</td>"
            f"<td>{_h(iso.isolation_source or iso.host or '—')}</td>"
            f"<td><code>{_h(iso.pds_acc)}</code></td>"
            f"<td>{_h(iso.collection_date or '—')}</td>"
            f"<td>{_h(iso.geo_loc_name or '—')}</td>"
            f"</tr>"
        )
    return (
        f"<h3><span class='badge badge-near'>≤{threshold} SNPs</span> "
        f"<span class='count'>{len(nns)} nonhuman isolate(s)</span></h3>"
        "<table><thead><tr>"
        "<th>Isolate</th><th>min_diff</th><th>Source</th><th>Own cluster</th>"
        "<th>Collected</th><th>Geography</th>"
        "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
    )


def render_html(
    run_date: date,
    events_by_pathogen: dict[str, list[Event]],
    mixed_clusters_by_pathogen: dict[str, list[Cluster]],
    near_neighbors_by_pathogen: dict[str, dict[int, list[CrossClusterNearNeighbor]]],
) -> str:
    total_events = sum(len(v) for v in events_by_pathogen.values())
    parts: list[str] = []
    parts.append(f"<!doctype html><html><head><meta charset='utf-8'>"
                 f"<title>Pathogen Detection Digest — {run_date.isoformat()}</title>"
                 f"<style>{_HTML_STYLE}</style></head><body>")
    parts.append(f"<h1>NCBI Pathogen Detection — Daily Digest</h1>")
    parts.append(
        f"<p class='meta'>{run_date.strftime('%A, %B %d, %Y')} · "
        f"<strong>{total_events}</strong> new event(s) across "
        f"{len(config.PATHOGENS)} pathogens · "
        f"recent window: {config.RECENT_WINDOW_DAYS} days</p>"
    )

    for pathogen in config.PATHOGENS:
        events = events_by_pathogen.get(pathogen, [])
        mixed = mixed_clusters_by_pathogen.get(pathogen, [])
        neighbors = near_neighbors_by_pathogen.get(pathogen, {})

        parts.append(f"<h2>{_h(pathogen)} "
                     f"<span class='count'>· {len(events)} event(s)</span></h2>")

        parts.append(f"<h3>Alerts</h3>")
        parts.append(_events_table(events))

        parts.append(f"<h3>Active mixed clusters <span class='count'>"
                     f"({len(mixed)} in last {config.RECENT_WINDOW_DAYS} days)</span></h3>")
        parts.append(_mixed_table(mixed))

        nn_total = sum(len(v) for v in neighbors.values())
        if nn_total:
            parts.append(f"<h3>Tight cross-cluster nonhuman neighbors "
                         f"<span class='count'>(early-warning)</span></h3>")
            for thresh in config.SNP_THRESHOLDS:
                parts.append(_neighbors_table(neighbors.get(thresh, []), thresh))

    parts.append(
        "<div class='footer'>"
        "Generated by <code>pathogen-alerts</code>. "
        "Source: <a href='https://www.ncbi.nlm.nih.gov/pathogens/'>"
        "NCBI Pathogen Detection</a>. "
        "Thresholds are upper bounds derived from per-isolate <code>min_same</code> / "
        "<code>min_diff</code>; verify clusters of interest directly at NCBI."
        "</div></body></html>"
    )
    return "".join(parts)
